import { createElement } from 'lwc';
import Lwcejercicio1jb from 'c/lwcejercicio1jb';

describe('c-lwcejercicio1-jb', () => {
    afterEach(() => {
       
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwcejercicio1-jb', {
            is: Lwcejercicio1jb
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});//fin